import { useState, useEffect } from 'react';
import RenamableTitle from '../RenamableTitle';

const TONE_COLORS = {
  Enthusiastic: '#f59e0b',
  Professional: '#2563eb',
  Confident: '#8b5cf6',
};

function ToneTag({ tone }) {
  const color = TONE_COLORS[tone] || '#64748b';
  return (
    <span className="summary-tone-tag" style={{ background: `${color}18`, color, borderColor: `${color}40` }}>
      {tone}
    </span>
  );
}

export default function Step5Summary({ data, onChange, sectionTitles, onRename }) {
  const summary = data.summary || '';
  const charLen = summary.length;
  const metTarget = charLen >= 400;

  const [loading, setLoading] = useState(false);
  const [suggestions, setSuggestions] = useState([]);
  const [apiError, setApiError] = useState('');
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);

  const jobTitle = (data.personalInfo || {}).jobTarget || '';

  // Build a brief experience summary to help Claude write a better summary
  const experienceSummary = (data.experience || [])
    .slice(0, 2)
    .map(e => `${e.jobTitle || ''}${e.company ? ` at ${e.company}` : ''}`)
    .filter(Boolean)
    .join(', ');

  // Auto-generate suggestions when job title exists and summary is short
  useEffect(() => {
    if (jobTitle && !summary && !hasAutoGenerated) {
      setHasAutoGenerated(true);
      handleGenerate();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const handleGenerate = async () => {
    setLoading(true);
    setApiError('');
    setSuggestions([]);
    try {
      const resumeContext = {
        jobTitle,
        experience: (data.experience || []).slice(0, 3).map(e => ({
          jobTitle: e.jobTitle,
          company: e.company,
          description: (e.description || '').slice(0, 300),
        })),
        skills: (data.skillsWithLevel || []).slice(0, 10).map(s => s.name),
      };
      const res = await fetch('/api/suggest-content', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          section: 'summary',
          jobTitle,
          currentContent: summary,
          experienceSummary,
          resumeData: resumeContext,
        }),
      });
      if (!res.ok) throw new Error('API error');
      const json = await res.json();
      if (json.summaries) setSuggestions(json.summaries);
    } catch {
      setApiError('Could not generate suggestions. Try again.');
    } finally {
      setLoading(false);
    }
  };

  const handleUse = (text) => {
    onChange({ summary: text });
    setSuggestions([]);
  };

  const handleRewrite = async (text) => {
    onChange({ summary: text });
    setSuggestions([]);
    // Immediately re-generate from the new text
    setTimeout(handleGenerate, 100);
  };

  return (
    <div className="wizard-step">
      <div className="wizard-step-header">
        <RenamableTitle
          value={(sectionTitles || {}).summary}
          defaultValue="Professional Summary"
          onChange={v => onRename('summary', v)}
        />
        <p className="wizard-step-subtitle">
          Write 2-4 short, energetic sentences about how great you are. Mention the role and what you did. What were the big achievements?
        </p>
      </div>

      {/* Main editor */}
      <div className="wizard-field wizard-field-full">
        <div className="wizard-rte-toolbar">
          <label className="wizard-label" style={{ marginBottom: 0 }}>Your Summary</label>
          <button
            type="button"
            className="wizard-phrases-btn"
            onClick={handleGenerate}
            disabled={loading}
          >
            {loading ? '⏳ Generating…' : '✨ Pre-written phrases +'}
          </button>
        </div>

        <textarea
          className="wizard-textarea"
          rows={6}
          placeholder={`Dedicated ${jobTitle || 'professional'} with X+ years of experience driving results in [industry]. Proven track record of [key achievement]. Passionate about [area] and committed to [value]...`}
          value={summary}
          onChange={e => onChange({ summary: e.target.value })}
        />

        <div className="wizard-textarea-meta">
          <span className={`wizard-char-count ${metTarget ? 'met' : charLen >= 200 ? 'partial' : ''}`}>
            {charLen} / 400+
            {metTarget && <span className="wizard-char-good"> ✓ Great length</span>}
            {!metTarget && charLen >= 200 && <span className="wizard-char-ok"> ✓ Good — aim for 400+</span>}
          </span>
        </div>

        <div className="wizard-recruiter-tip">
          <span className="wizard-tip-icon">💡</span>
          <p>
            <strong>Recruiter tip:</strong> Summaries between 400–600 characters get significantly more attention. Mention your target role, top skills, and one key achievement.
          </p>
        </div>
      </div>

      {/* AI error */}
      {apiError && (
        <p className="wizard-improve-error" style={{ marginTop: '0.5rem' }}>{apiError}</p>
      )}

      {/* AI-generated suggestions */}
      {suggestions.length > 0 && (
        <div className="summary-suggestions">
          <div className="summary-suggestions-header">
            <span>AI-generated alternatives</span>
            <button
              type="button"
              className="wizard-suggestions-refresh"
              onClick={handleGenerate}
              disabled={loading}
            >
              ↻ Regenerate
            </button>
          </div>

          {suggestions.map((s, i) => (
            <div key={i} className="summary-suggestion-card">
              <div className="summary-suggestion-top">
                <ToneTag tone={s.tone} />
                <div className="summary-suggestion-actions">
                  <button
                    type="button"
                    className="summary-btn-rewrite"
                    onClick={() => handleRewrite(s.text)}
                  >
                    Rewrite
                  </button>
                  <button
                    type="button"
                    className="summary-btn-use"
                    onClick={() => handleUse(s.text)}
                  >
                    Use this →
                  </button>
                </div>
              </div>
              <p className="summary-suggestion-text">{s.text}</p>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
