export const TEMPLATES = [
  // ── Original 6 ────────────────────────────────────────────────────────────
  {
    id: 'classic',
    name: 'Classic',
    description: 'Traditional single-column, clean and conservative',
    bestFor: ['Corporate', 'Finance', 'Legal'],
    accent: '#2E5A88',
    categories: ['Simple', 'ATS'],
    ats: true,
  },
  {
    id: 'modern',
    name: 'Modern',
    description: 'Two-column layout with sidebar for skills & contact',
    bestFor: ['Tech', 'Design', 'Marketing'],
    accent: '#4A90D9',
    categories: ['Modern', 'Two-Column'],
    ats: false,
  },
  {
    id: 'minimal',
    name: 'Minimal',
    description: 'Elegant typography with generous white space',
    bestFor: ['Creative', 'Executive'],
    accent: '#555555',
    categories: ['Simple', 'ATS'],
    ats: true,
  },
  {
    id: 'bold',
    name: 'Bold',
    description: 'Strong section headers with accent color bars',
    bestFor: ['Sales', 'Management'],
    accent: '#E63946',
    categories: ['Modern'],
    ats: false,
  },
  {
    id: 'tech',
    name: 'Tech',
    description: 'Code-inspired monospace aesthetic with structured layout',
    bestFor: ['Developers', 'Engineers'],
    accent: '#2D9CDB',
    categories: ['Modern', 'Creative'],
    ats: false,
  },
  {
    id: 'creative',
    name: 'Creative',
    description: 'Gradient header with skill chips — visually distinctive',
    bestFor: ['Designers', 'Artists'],
    accent: '#9B59B6',
    categories: ['Creative'],
    ats: false,
  },

  // ── New 9 ─────────────────────────────────────────────────────────────────
  {
    id: 'executive',
    name: 'Executive',
    description: 'Premium sidebar layout with authoritative presence',
    bestFor: ['C-Suite', 'Directors', 'VP'],
    accent: '#1e293b',
    categories: ['Professional', 'Two-Column'],
    ats: false,
  },
  {
    id: 'academic',
    name: 'Academic',
    description: 'Formal scholarly layout with education-first structure',
    bestFor: ['Professors', 'Researchers', 'PhDs'],
    accent: '#5C4033',
    categories: ['Professional', 'ATS'],
    ats: true,
  },
  {
    id: 'compact',
    name: 'Compact',
    description: 'Dense layout that fits maximum content in one page',
    bestFor: ['Senior', 'Career Change'],
    accent: '#374151',
    categories: ['Simple', 'ATS'],
    ats: true,
  },
  {
    id: 'timeline',
    name: 'Timeline',
    description: 'Visual timeline showcasing your career progression',
    bestFor: ['Project Managers', 'Creatives'],
    accent: '#0f766e',
    categories: ['Modern'],
    ats: false,
  },
  {
    id: 'elegant',
    name: 'Elegant',
    description: 'Refined serif typography with decorative accents',
    bestFor: ['Law', 'Finance', 'Consulting'],
    accent: '#9c7c3b',
    categories: ['Professional', 'Simple'],
    ats: true,
  },
  {
    id: 'ats-strict',
    name: 'ATS-Strict',
    description: 'Plainest possible format — guaranteed ATS pass',
    bestFor: ['All Industries', 'Large Corps'],
    accent: '#1a1a1a',
    categories: ['ATS', 'Simple'],
    ats: true,
  },
  {
    id: 'developer',
    name: 'Developer',
    description: 'Terminal header with visual skill-level bars',
    bestFor: ['Engineers', 'Fullstack', 'DevOps'],
    accent: '#10b981',
    categories: ['Modern', 'Creative'],
    ats: false,
  },
  {
    id: 'vivid',
    name: 'Vivid',
    description: 'Bold full-width accent bars — maximum visual impact',
    bestFor: ['Marketing', 'Brand', 'PR'],
    accent: '#dc2626',
    categories: ['Creative'],
    ats: false,
  },
  {
    id: 'federal',
    name: 'Federal',
    description: 'Government resume format with formal detailed sections',
    bestFor: ['Government', 'Military', 'Public Sector'],
    accent: '#1d4ed8',
    categories: ['Professional', 'ATS'],
    ats: true,
  },
];

export const TEMPLATE_CATEGORIES = ['All', 'Simple', 'Modern', 'Creative', 'Professional', 'ATS', 'Two-Column'];

export const DEFAULT_RESUME_DATA = {
  selectedTemplate: 'classic',
  personalInfo: {
    fullName: '',
    email: '',
    phone: '',
    location: '',
    linkedin: '',
    github: '',
    website: '',
  },
  summary: '',
  experience: [],
  education: [],
  skills: {
    technical: [],
    soft: [],
    tools: [],
    languages: [],
    certifications: [],
  },
  projects: [],
  certifications: [],
  customSections: [],
  sectionOrder: ['summary', 'experience', 'education', 'skills', 'projects', 'certifications'],
  hiddenSections: [],
  design: {
    accentColor: '',
    fontFamily: 'Inter',
    spacing: 'normal',
    layout: 'centered',
  },
};
